import Head from "next/head";
import Link from "next/link";
import {
  Box,
  Text,
  Spacer,
  Avatar,
  Grid,
  Flex,
  InputGroup,
  Icon,
  Input,
  Wrap,
  WrapItem,
  Tag,
  InputRightElement,
  GridItem,
  Image,
  VStack,
  HStack,
  Select,
  Textarea,
  Button,
  Heading,
} from "@chakra-ui/react";
import {
  CalendarIcon,
  PhoneIcon,
  BellIcon,
  AtSignIcon,
  Search2Icon,
} from "@chakra-ui/icons";
import { api } from "~/utils/api";
import styles from "./index.module.css";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Innersonic</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box h="100vh">
        <Box
          w="100%"
          bg="#6A67F1"
          p={4}
          display="flex"
          alignItems="center"
          gap={4}
          justifyContent="space-between"
          h="80px"
        >
          <Box as="span" color="white" fontWeight="bold" fontSize="lg">
            Innersonic
          </Box>
          <Box
            display="flex"
            flexDirection="row"
            justifyContent="center"
            alignItems="center"
            w="150px"
            h="40px"
            bg="#201BFF"
            borderRadius="9999px"
            gap={4}
            cursor="pointer"
          >
            <CalendarIcon color="white" />
            <Text color="white" fontSize="md">
              Dashboard
            </Text>
          </Box>
          <Box
            display="flex"
            flexDirection="row"
            justifyContent="space-evenly"
            alignItems="center"
            w="150px"
            h="40px"
            bg="white"
            borderRadius="9999px"
            gap={4}
            cursor="pointer"
          >
            <CalendarIcon color="#201BFF" />
            <Text color="#201BFF" fontSize="md">
              Post
            </Text>
          </Box>

          <Box
            display="flex"
            flexDirection="row"
            justifyContent="space-evenly"
            alignItems="center"
            w="150px"
            h="40px"
            bg="white"
            borderRadius="9999px"
            gap={4}
            cursor="pointer"
          >
            <CalendarIcon color="#201BFF" />
            <Text color="#201BFF" fontSize="md">
              Report
            </Text>
          </Box>

          <Spacer />

          <Box display="flex" alignItems="center" gap="2">
            <Box
              display="flex"
              justifyContent="center"
              alignItems="center"
              borderRadius="50%"
              width="48px" // Adjust the width as needed
              height="48px" // Adjust the height as needed
              bg="#201BFF" // Set your desired background color
              color="white" // Set your desired icon color
              cursor="pointer"
            >
              <BellIcon boxSize={25} />
            </Box>
            <Box
              display="flex"
              justifyContent="center"
              alignItems="center"
              borderRadius="50%"
              width="48px" // Adjust the width as needed
              height="48px" // Adjust the height as needed
              bg="#201BFF" // Set your desired background color
              color="white" // Set your desired icon color
              cursor="pointer"
            >
              <Avatar name="Dan Abrahmov" src="https://bit.ly/dan-abramov" />
            </Box>
          </Box>
        </Box>
        <Flex height="calc(100vh - 100px)" p={4} w="calc(100% - 2rem)" gap={6}>
          <Flex direction="column" width="40%" height="100%" pr={2}>
            <Box
              bg="gray.50"
              borderRadius="md"
              mb={2}
              flex="1"
              m={4}
              textAlign="center"
            >
              <Box
                as="span"
                color="black"
                fontWeight="bold"
                fontSize="xx-large"
              >
                Trending Topics
              </Box>

              <Box w="full" p={4}>
                <InputGroup>
                  <InputRightElement pointerEvents="none">
                    <Icon as={Search2Icon} color="gray.500" />
                  </InputRightElement>
                  <Input type="text" placeholder="Search for trends" />
                </InputGroup>
              </Box>

              <Wrap spacing="3" justify="center">
                <WrapItem>
                  <Tag
                    borderRadius="full"
                    variant="solid"
                    colorScheme="purple"
                    px="3"
                    py="1"
                    fontSize="large"
                  >
                    #FitnessGearForSpring
                  </Tag>
                </WrapItem>
                <WrapItem>
                  <Tag
                    borderRadius="full"
                    variant="solid"
                    colorScheme="purple"
                    px="3"
                    py="1"
                    fontSize="large"
                  >
                    #OOTD
                  </Tag>
                </WrapItem>
                {/* ... more tags */}
                <WrapItem>
                  <Tag
                    borderRadius="full"
                    variant="solid"
                    colorScheme="purple"
                    px="3"
                    py="1"
                    fontSize="large"
                  >
                    #BaroquePeral
                  </Tag>
                </WrapItem>
                <WrapItem>
                  <Tag
                    borderRadius="full"
                    variant="solid"
                    colorScheme="purple"
                    px="3"
                    py="1"
                    fontSize="large"
                  >
                    #YK2
                  </Tag>
                </WrapItem>
                <WrapItem>
                  <Tag
                    borderRadius="full"
                    variant="solid"
                    colorScheme="purple"
                    px="3"
                    py="1"
                    fontSize="large"
                  >
                    #90's
                  </Tag>
                </WrapItem>
                <WrapItem>
                  <Tag
                    borderRadius="full"
                    variant="solid"
                    colorScheme="purple"
                    px="3"
                    py="1"
                    fontSize="large"
                  >
                    #KoreanStyle
                  </Tag>
                </WrapItem>
                <WrapItem>
                  <Tag
                    borderRadius="full"
                    variant="solid"
                    colorScheme="purple"
                    px="3"
                    py="1"
                    fontSize="large"
                  >
                    #NCT
                  </Tag>
                </WrapItem>
                <WrapItem>
                  <Tag
                    borderRadius="full"
                    variant="solid"
                    colorScheme="purple"
                    px="3"
                    py="1"
                    fontSize="large"
                  >
                    #GOT7
                  </Tag>
                </WrapItem>
                <WrapItem>
                  <Tag
                    borderRadius="full"
                    variant="solid"
                    colorScheme="purple"
                    px="3"
                    py="1"
                    fontSize="large"
                  >
                    #MeanGirl
                  </Tag>
                </WrapItem>
                <WrapItem>
                  <Tag
                    borderRadius="full"
                    variant="solid"
                    colorScheme="purple"
                    px="3"
                    py="1"
                    fontSize="large"
                  >
                    #TaylorSwiftConcert
                  </Tag>
                </WrapItem>
                <WrapItem>
                  <Tag
                    borderRadius="full"
                    variant="solid"
                    colorScheme="purple"
                    px="3"
                    py="1"
                    fontSize="large"
                  >
                    #BaroquePeral
                  </Tag>
                </WrapItem>

                {/* ... repeat for each hashtag */}
              </Wrap>
            </Box>

            {/* Bottom box - 50% height */}
            <Box
              bg="gray.50"
              borderRadius="md"
              flex="1"
              m={4}
              textAlign="center"
            >
              <Box
                as="span"
                color="black"
                fontWeight="bold"
                fontSize="xx-large"
              >
                Discover Topics
              </Box>

              <Box w="full" p={4}>
                <InputGroup>
                  <InputRightElement pointerEvents="none">
                    <Icon as={Search2Icon} color="gray.500" />
                  </InputRightElement>
                  <Input type="text" placeholder="Search for trends" />
                </InputGroup>
              </Box>

              <Box>
                <Grid templateColumns="repeat(4, 1fr)" gap={2}>
                  <GridItem colSpan={2} rowSpan={2}>
                    <Image
                      src="/cute_image1.jpeg"
                      alt="Image 1"
                      objectFit="cover"
                      width="100%"
                      height="100%"
                    />
                  </GridItem>
                  <GridItem colSpan={1}>
                    <Image
                      src="/cute_image2.jpeg"
                      alt="Image 2"
                      objectFit="cover"
                      width="100%"
                      height="100%"
                    />
                  </GridItem>
                  <GridItem colSpan={1} rowSpan={2}>
                    <Image
                      src="/cute_image3.jpeg"
                      alt="Image 3"
                      objectFit="cover"
                      width="100%"
                      height="100%"
                    />
                  </GridItem>
                  <GridItem colSpan={1}>
                    <Image
                      src="/cute_image4.jpeg"
                      alt="Image 4"
                      objectFit="cover"
                      width="100%"
                      height="100%"
                    />
                  </GridItem>
                  {/* <GridItem colSpan={2}>
                    <Image
                      src="/cute_image5.webp"
                      alt="Image 5"
                      objectFit="cover"
                      width="100%"
                      height="100%"
                    />
                  </GridItem> */}
                </Grid>
              </Box>
            </Box>
          </Flex>

          {/* Right Side - 60% width */}
          <Box
            width="60%"
            height="100%"
            pl={2}
            bg="gray.50"
            borderRadius="md"
            m={4}
            textAlign="center"
          >
            <Box as="span" color="black" fontWeight="bold" fontSize="xx-large">
              Generate Project
            </Box>

            <VStack spacing={4} p={4}>
              <Heading size="md" alignSelf="flex-start">
                For Post
              </Heading>

              <HStack width="full" spacing={4}>
                <Select placeholder="Pick platform" w="full">
                  {/* Option values go here */}
                </Select>
                <Select placeholder="Pick a tone" w="full">
                  {/* Option values go here */}
                </Select>
              </HStack>

              <Textarea
                placeholder="Describe your project"
                size="sm"
                resize="vertical"
              />

              <Button colorScheme="blue" size="md" alignSelf="center">
                Generate my post
              </Button>
            </VStack>

            <VStack spacing={4} p={4}>
              <Heading size="md" alignSelf="flex-start">
                For Idea
              </Heading>

              

              <Textarea
                placeholder="Describe a design style, pick a keyword or both"
                size="sm"
                resize="vertical"
              />

              <Button colorScheme="blue" size="md" alignSelf="center">
                Generate my post
              </Button>
            </VStack>
          </Box>
        </Flex>
      </Box>
      {/* <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
             <span className={styles.pinkSpan}>Innersonic</span> App
          </h1>
        </div>
      </main> */}
    </>
  );
}
