import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import styles from "./index.module.css";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Innersonic</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
             <span className={styles.pinkSpan}>Innersonic</span> App
          </h1>
          <div className={styles.cardRow}>
            <Link
              className={styles.card}
              href="."
            >
              <h3 className={styles.cardTitle}>Hello from Next</h3>
              <div className={styles.cardText}>
                This is a dummy card as well.
              </div>
            </Link>
            <Link
              className={styles.card}
              href="."       
            >
              <h3 className={styles.cardTitle}>Create Cards</h3>
              <div className={styles.cardText}>
                This is a dummy card componnet
              </div>
            </Link>
          </div>
          <p className={styles.showcaseText}>
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
}
