import Head from "next/head";
import Link from "next/link";
import { Box, Text, Spacer, Avatar, Grid, Flex } from "@chakra-ui/react";
import {
  CalendarIcon,
  PhoneIcon,
  BellIcon,
  AtSignIcon,
} from "@chakra-ui/icons";
import { api } from "~/utils/api";
import styles from "./index.module.css";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Innersonic</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box h="100vh">
        <Box
          w="100%"
          bg="#6A67F1"
          p={4}
          display="flex"
          alignItems="center"
          gap={4}
          justifyContent="space-between"
          h="80px"
        >
          <Box as="span" color="white" fontWeight="bold" fontSize="lg">
            Innersonic
          </Box>
          <Box
            display="flex"
            flexDirection="row"
            justifyContent="center"
            alignItems="center"
            w="150px"
            h="40px"
            bg="#201BFF"
            borderRadius="9999px"
            gap={4}
            cursor="pointer"
          >
            <CalendarIcon color="white" />
            <Text color="white" fontSize="md">
              Dashboard
            </Text>
          </Box>
          <Box
            display="flex"
            flexDirection="row"
            justifyContent="space-evenly"
            alignItems="center"
            w="150px"
            h="40px"
            bg="white"
            borderRadius="9999px"
            gap={4}
            cursor="pointer"
          >
            <CalendarIcon color="#201BFF" />
            <Text color="#201BFF" fontSize="md">
              Post
            </Text>
          </Box>

          <Box
            display="flex"
            flexDirection="row"
            justifyContent="space-evenly"
            alignItems="center"
            w="150px"
            h="40px"
            bg="white"
            borderRadius="9999px"
            gap={4}
            cursor="pointer"
          >
            <CalendarIcon color="#201BFF" />
            <Text color="#201BFF" fontSize="md">
              Report
            </Text>
          </Box>

          <Spacer />

          <Box display="flex" alignItems="center" gap="2">
            <Box
              display="flex"
              justifyContent="center"
              alignItems="center"
              borderRadius="50%"
              width="48px" // Adjust the width as needed
              height="48px" // Adjust the height as needed
              bg="#201BFF" // Set your desired background color
              color="white" // Set your desired icon color
              cursor="pointer"
            >
              <BellIcon boxSize={25} />
            </Box>
            <Box
              display="flex"
              justifyContent="center"
              alignItems="center"
              borderRadius="50%"
              width="48px" // Adjust the width as needed
              height="48px" // Adjust the height as needed
              bg="#201BFF" // Set your desired background color
              color="white" // Set your desired icon color
              cursor="pointer"
            >
              <Avatar name="Dan Abrahmov" src="https://bit.ly/dan-abramov" />
            </Box>
          </Box>
        </Box>
        <Flex height="calc(100vh - 100px)" p={4} w="calc(100% - 2rem)" gap={6}>
          {/* Left Side - 40% width */}
          <Flex direction="column" width="40%" height="100%" pr={2} >
            {/* Top box - 50% height */}
            <Box bg="grey.200" borderRadius="md" mb={2} flex="1" m={4}>
              {/* Content goes here */}
            </Box>

            {/* Bottom box - 50% height */}
            <Box bg="grey.300" borderRadius="md" flex="1" m={4}>
              {/* Content goes here */}
            </Box>
          </Flex>

          {/* Right Side - 60% width */}
          <Box
            width="60%"
            height="100%"
            pl={2}
            bg="grey.100"
            borderRadius="md"
            m={4}
          >
            {/* Content goes here */}
          </Box>
        </Flex>
      </Box>
      {/* <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
             <span className={styles.pinkSpan}>Innersonic</span> App
          </h1>
        </div>
      </main> */}
    </>
  );
}
